# Generated by Django 4.1.5 on 2023-01-27 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chef',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can view history')]},
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='birth_data',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='chef',
            old_name='join_data',
            new_name='join_date',
        ),
    ]
