# Generated by Django 4.1.5 on 2023-01-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_recipe_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='collection',
            field=models.ManyToManyField(to='core.collection'),
        ),
    ]
