# Generated by Django 4.1.5 on 2023-02-08 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_category_featured_collection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='chef',
            new_name='user',
        ),
    ]
