# Generated by Django 4.1.5 on 2023-04-02 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='chef',
        ),
    ]
