# Generated by Django 4.1.5 on 2023-04-02 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_user_recipe_chef'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='chef',
            new_name='user',
        ),
    ]
